[local]
localhost


[mongodb]
mongodb.venkatapp.fun

[redis]
redis.venkatapp.fun

[mysql]
mysql.venkatapp.fun

[rabbitmq]
rabbitmq.venkatapp.fun

[catalogue]
catalogue.venkatapp.fun

[cart]
cart.venkatapp.fun

[user]
user.venkatapp.fun

[shipping]
shipping.venkatapp.fun

[payment]
payment.venkatapp.fun

[frontend]
frontend.venkatapp.fun



[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321